from typing import List, Optional
from pydantic import BaseModel, Field
from datetime import datetime


class BalanceSheetItem(BaseModel):
    """Single balance sheet item"""
    treasury_shares_number: Optional[float] = Field(None, description="Number of treasury shares")
    ordinary_shares_number: Optional[float] = Field(None, description="Number of ordinary shares")
    share_issued: Optional[float] = Field(None, description="Number of shares issued")
    net_debt: Optional[float] = Field(None, description="Net debt")
    total_debt: Optional[float] = Field(None, description="Total debt")
    tangible_book_value: Optional[float] = Field(None, description="Tangible book value")
    invested_capital: Optional[float] = Field(None, description="Invested capital")
    working_capital: Optional[float] = Field(None, description="Working capital")
    net_tangible_assets: Optional[float] = Field(None, description="Net tangible assets")
    capital_lease_obligations: Optional[float] = Field(None, description="Capital lease obligations")
    common_stock_equity: Optional[float] = Field(None, description="Common stock equity")
    total_capitalization: Optional[float] = Field(None, description="Total capitalization")
    total_equity_gross_minority_interest: Optional[float] = Field(None, description="Total equity including minority interest")
    stockholders_equity: Optional[float] = Field(None, description="Stockholders equity")
    gains_losses_not_affecting_retained_earnings: Optional[float] = Field(None, description="Gains/losses not affecting retained earnings")
    other_equity_adjustments: Optional[float] = Field(None, description="Other equity adjustments")
    retained_earnings: Optional[float] = Field(None, description="Retained earnings")
    capital_stock: Optional[float] = Field(None, description="Capital stock")
    common_stock: Optional[float] = Field(None, description="Common stock")
    total_liabilities_net_minority_interest: Optional[float] = Field(None, description="Total liabilities net of minority interest")
    total_non_current_liabilities_net_minority_interest: Optional[float] = Field(None, description="Total non-current liabilities net of minority interest")
    other_non_current_liabilities: Optional[float] = Field(None, description="Other non-current liabilities")
    tradeand_other_payables_non_current: Optional[float] = Field(None, description="Trade and other payables non-current")
    long_term_debt_and_capital_lease_obligation: Optional[float] = Field(None, description="Long-term debt and capital lease obligation")
    long_term_capital_lease_obligation: Optional[float] = Field(None, description="Long-term capital lease obligation")
    long_term_debt: Optional[float] = Field(None, description="Long-term debt")
    current_liabilities: Optional[float] = Field(None, description="Current liabilities")
    other_current_liabilities: Optional[float] = Field(None, description="Other current liabilities")
    current_deferred_liabilities: Optional[float] = Field(None, description="Current deferred liabilities")
    current_deferred_revenue: Optional[float] = Field(None, description="Current deferred revenue")
    current_debt_and_capital_lease_obligation: Optional[float] = Field(None, description="Current debt and capital lease obligation")
    current_capital_lease_obligation: Optional[float] = Field(None, description="Current capital lease obligation")
    current_debt: Optional[float] = Field(None, description="Current debt")
    other_current_borrowings: Optional[float] = Field(None, description="Other current borrowings")
    commercial_paper: Optional[float] = Field(None, description="Commercial paper")
    payables_and_accrued_expenses: Optional[float] = Field(None, description="Payables and accrued expenses")
    payables: Optional[float] = Field(None, description="Payables")
    other_payable: Optional[float] = Field(None, description="Other payable")
    total_tax_payable: Optional[float] = Field(None, description="Total tax payable")
    income_tax_payable: Optional[float] = Field(None, description="Income tax payable")
    accounts_payable: Optional[float] = Field(None, description="Accounts payable")
    total_assets: Optional[float] = Field(None, description="Total assets")
    total_non_current_assets: Optional[float] = Field(None, description="Total non-current assets")
    other_non_current_assets: Optional[float] = Field(None, description="Other non-current assets")
    non_current_deferred_assets: Optional[float] = Field(None, description="Non-current deferred assets")
    non_current_deferred_taxes_assets: Optional[float] = Field(None, description="Non-current deferred tax assets")
    investments_and_advances: Optional[float] = Field(None, description="Investments and advances")
    other_investments: Optional[float] = Field(None, description="Other investments")
    investmentin_financial_assets: Optional[float] = Field(None, description="Investment in financial assets")
    available_for_sale_securities: Optional[float] = Field(None, description="Available for sale securities")
    net_ppe: Optional[float] = Field(None, description="Net property, plant and equipment")
    accumulated_depreciation: Optional[float] = Field(None, description="Accumulated depreciation")
    gross_ppe: Optional[float] = Field(None, description="Gross property, plant and equipment")
    leases: Optional[float] = Field(None, description="Leases")
    other_properties: Optional[float] = Field(None, description="Other properties")
    machinery_furniture_equipment: Optional[float] = Field(None, description="Machinery, furniture and equipment")
    land_and_improvements: Optional[float] = Field(None, description="Land and improvements")
    properties: Optional[float] = Field(None, description="Properties")
    current_assets: Optional[float] = Field(None, description="Current assets")
    other_current_assets: Optional[float] = Field(None, description="Other current assets")
    inventory: Optional[float] = Field(None, description="Inventory")
    receivables: Optional[float] = Field(None, description="Receivables")
    other_receivables: Optional[float] = Field(None, description="Other receivables")
    accounts_receivable: Optional[float] = Field(None, description="Accounts receivable")
    cash_cash_equivalents_and_short_term_investments: Optional[float] = Field(None, description="Cash, cash equivalents and short-term investments")
    other_short_term_investments: Optional[float] = Field(None, description="Other short-term investments")
    cash_and_cash_equivalents: Optional[float] = Field(None, description="Cash and cash equivalents")
    cash_equivalents: Optional[float] = Field(None, description="Cash equivalents")
    cash_financial: Optional[float] = Field(None, description="Financial cash")
    date: Optional[datetime] = Field(None, description="Statement date")
