from typing import List, Optional
from pydantic import BaseModel, Field
from datetime import datetime


class IncomeStmtItem(BaseModel):
    """Single income statement item"""
    tax_effect_of_unusual_items: Optional[float] = Field(None, description="Tax effect of unusual items")
    tax_rate_for_calcs: Optional[float] = Field(None, description="Tax rate used for calculations")
    normalized_ebitda: Optional[float] = Field(None, description="Normalized EBITDA")
    net_income_from_continuing_operation_net_minority_interest: Optional[float] = Field(None, description="Net income from continuing operations net of minority interest")
    reconciled_depreciation: Optional[float] = Field(None, description="Reconciled depreciation")
    reconciled_cost_of_revenue: Optional[float] = Field(None, description="Reconciled cost of revenue")
    ebitda: Optional[float] = Field(None, description="EBITDA")
    ebit: Optional[float] = Field(None, description="EBIT")
    net_interest_income: Optional[float] = Field(None, description="Net interest income")
    interest_expense: Optional[float] = Field(None, description="Interest expense")
    interest_income: Optional[float] = Field(None, description="Interest income")
    normalized_income: Optional[float] = Field(None, description="Normalized income")
    net_income_from_continuing_and_discontinued_operation: Optional[float] = Field(None, description="Net income from continuing and discontinued operations")
    total_expenses: Optional[float] = Field(None, description="Total expenses")
    total_operating_income_as_reported: Optional[float] = Field(None, description="Total operating income as reported")
    diluted_average_shares: Optional[float] = Field(None, description="Diluted average shares")
    basic_average_shares: Optional[float] = Field(None, description="Basic average shares")
    diluted_eps: Optional[float] = Field(None, description="Diluted earnings per share")
    basic_eps: Optional[float] = Field(None, description="Basic earnings per share")
    diluted_niavailto_com_stockholders: Optional[float] = Field(None, description="Diluted net income available to common stockholders")
    net_income_common_stockholders: Optional[float] = Field(None, description="Net income to common stockholders")
    net_income: Optional[float] = Field(None, description="Net income")
    net_income_including_noncontrolling_interests: Optional[float] = Field(None, description="Net income including non-controlling interests")
    net_income_continuous_operations: Optional[float] = Field(None, description="Net income from continuous operations")
    tax_provision: Optional[float] = Field(None, description="Tax provision")
    pretax_income: Optional[float] = Field(None, description="Pre-tax income")
    other_income_expense: Optional[float] = Field(None, description="Other income/expense")
    other_non_operating_income_expenses: Optional[float] = Field(None, description="Other non-operating income/expenses")
    net_non_operating_interest_income_expense: Optional[float] = Field(None, description="Net non-operating interest income/expense")
    interest_expense_non_operating: Optional[float] = Field(None, description="Non-operating interest expense")
    interest_income_non_operating: Optional[float] = Field(None, description="Non-operating interest income")
    operating_income: Optional[float] = Field(None, description="Operating income")
    operating_expense: Optional[float] = Field(None, description="Operating expense")
    research_and_development: Optional[float] = Field(None, description="Research and development expenses")
    selling_general_and_administration: Optional[float] = Field(None, description="Selling, general and administration expenses")
    gross_profit: Optional[float] = Field(None, description="Gross profit")
    cost_of_revenue: Optional[float] = Field(None, description="Cost of revenue")
    total_revenue: Optional[float] = Field(None, description="Total revenue")
    operating_revenue: Optional[float] = Field(None, description="Operating revenue")
    date: Optional[datetime] = Field(None, description="Statement date")
