from typing import List, Optional
from pydantic import BaseModel, Field
from datetime import datetime


class FinancialMetricItem(BaseModel):
    """Financial metric item"""
    date: Optional[datetime] = Field(None, description="Statement date")
    market_cap: Optional[float] = Field(None, description="Market capitalization")
    enterprise_value: Optional[float] = Field(None, description="Enterprise value")
    dividends_and_other_cash_distributions: Optional[float] = Field(None, description="Dividends and other cash distributions")
    issuance_or_purchase_of_equity_shares: Optional[float] = Field(None, description="Issuance or purchase of equity shares")
    price_to_earnings_ratio: Optional[float] = Field(None, description="Price to earnings ratio")
    price_to_book_ratio: Optional[float] = Field(None, description="Price to book ratio")
    price_to_sales_ratio: Optional[float] = Field(None, description="Price to sales ratio")
    enterprise_value_to_ebitda_ratio: Optional[float] = Field(None, description="Enterprise value to EBITDA ratio")
    enterprise_value_to_revenue_ratio: Optional[float] = Field(None, description="Enterprise value to revenue ratio")
    free_cash_flow_yield: Optional[float] = Field(None, description="Free cash flow yield")
    peg_ratio: Optional[float] = Field(None, description="PEG ratio")
    gross_margin: Optional[float] = Field(None, description="Gross margin")
    operating_margin: Optional[float] = Field(None, description="Operating margin")
    net_margin: Optional[float] = Field(None, description="Net margin")
    return_on_equity: Optional[float] = Field(None, description="Return on equity")
    return_on_assets: Optional[float] = Field(None, description="Return on assets")
    return_on_invested_capital: Optional[float] = Field(None, description="Return on invested capital")
    asset_turnover: Optional[float] = Field(None, description="Asset turnover")
    inventory_turnover: Optional[float] = Field(None, description="Inventory turnover")
    receivables_turnover: Optional[float] = Field(None, description="Receivables turnover")
    days_sales_outstanding: Optional[float] = Field(None, description="Days sales outstanding")
    operating_cycle: Optional[float] = Field(None, description="Operating cycle")
    working_capital_turnover: Optional[float] = Field(None, description="Working capital turnover")
    current_ratio: Optional[float] = Field(None, description="Current ratio")
    quick_ratio: Optional[float] = Field(None, description="Quick ratio")
    cash_ratio: Optional[float] = Field(None, description="Cash ratio")
    operating_cash_flow_ratio: Optional[float] = Field(None, description="Operating cash flow ratio")
    debt_to_equity: Optional[float] = Field(None, description="Debt to equity ratio")
    debt_to_assets: Optional[float] = Field(None, description="Debt to assets ratio")
    interest_coverage: Optional[float] = Field(None, description="Interest coverage ratio")
    revenue_growth: Optional[float] = Field(None, description="Revenue growth rate")
    earnings_growth: Optional[float] = Field(None, description="Earnings growth rate")
    book_value_growth: Optional[float] = Field(None, description="Book value growth rate")
    earnings_per_share_growth: Optional[float] = Field(None, description="Earnings per share growth rate")
    free_cash_flow_growth: Optional[float] = Field(None, description="Free cash flow growth rate")
    operating_income_growth: Optional[float] = Field(None, description="Operating income growth rate")
    ebitda_growth: Optional[float] = Field(None, description="EBITDA growth rate")
    payout_ratio: Optional[float] = Field(None, description="Payout ratio")
    earnings_per_share: Optional[float] = Field(None, description="Earnings per share")
    book_value_per_share: Optional[float] = Field(None, description="Book value per share")
    free_cash_flow_per_share: Optional[float] = Field(None, description="Free cash flow per share")
    symbol: Optional[str] = Field(None, description="Stock symbol")
