from typing import List, Optional
from pydantic import BaseModel, Field
from datetime import datetime


class CashFlowItem(BaseModel):
    """Single cash flow statement item"""
    free_cash_flow: Optional[float] = Field(None, description="Free cash flow")
    repurchase_of_capital_stock: Optional[float] = Field(None, description="Repurchase of capital stock")
    repayment_of_debt: Optional[float] = Field(None, description="Repayment of debt")
    issuance_of_debt: Optional[float] = Field(None, description="Issuance of debt")
    issuance_of_capital_stock: Optional[float] = Field(None, description="Issuance of capital stock")
    capital_expenditure: Optional[float] = Field(None, description="Capital expenditure")
    interest_paid_supplemental_data: Optional[float] = Field(None, description="Interest paid supplemental data")
    income_tax_paid_supplemental_data: Optional[float] = Field(None, description="Income tax paid supplemental data")
    end_cash_position: Optional[float] = Field(None, description="End cash position")
    beginning_cash_position: Optional[float] = Field(None, description="Beginning cash position")
    changes_in_cash: Optional[float] = Field(None, description="Changes in cash")
    financing_cash_flow: Optional[float] = Field(None, description="Financing cash flow")
    cash_flow_from_continuing_financing_activities: Optional[float] = Field(None, description="Cash flow from continuing financing activities")
    net_other_financing_charges: Optional[float] = Field(None, description="Net other financing charges")
    cash_dividends_paid: Optional[float] = Field(None, description="Cash dividends paid")
    common_stock_dividend_paid: Optional[float] = Field(None, description="Common stock dividend paid")
    net_common_stock_issuance: Optional[float] = Field(None, description="Net common stock issuance")
    common_stock_payments: Optional[float] = Field(None, description="Common stock payments")
    common_stock_issuance: Optional[float] = Field(None, description="Common stock issuance")
    net_issuance_payments_of_debt: Optional[float] = Field(None, description="Net issuance/payments of debt")
    net_short_term_debt_issuance: Optional[float] = Field(None, description="Net short-term debt issuance")
    net_long_term_debt_issuance: Optional[float] = Field(None, description="Net long-term debt issuance")
    long_term_debt_payments: Optional[float] = Field(None, description="Long-term debt payments")
    long_term_debt_issuance: Optional[float] = Field(None, description="Long-term debt issuance")
    investing_cash_flow: Optional[float] = Field(None, description="Investing cash flow")
    cash_flow_from_continuing_investing_activities: Optional[float] = Field(None, description="Cash flow from continuing investing activities")
    net_other_investing_changes: Optional[float] = Field(None, description="Net other investing changes")
    net_investment_purchase_and_sale: Optional[float] = Field(None, description="Net investment purchase and sale")
    sale_of_investment: Optional[float] = Field(None, description="Sale of investment")
    purchase_of_investment: Optional[float] = Field(None, description="Purchase of investment")
    net_business_purchase_and_sale: Optional[float] = Field(None, description="Net business purchase and sale")
    purchase_of_business: Optional[float] = Field(None, description="Purchase of business")
    net_ppe_purchase_and_sale: Optional[float] = Field(None, description="Net property, plant and equipment purchase and sale")
    purchase_of_ppe: Optional[float] = Field(None, description="Purchase of property, plant and equipment")
    operating_cash_flow: Optional[float] = Field(None, description="Operating cash flow")
    cash_flow_from_continuing_operating_activities: Optional[float] = Field(None, description="Cash flow from continuing operating activities")
    change_in_working_capital: Optional[float] = Field(None, description="Change in working capital")
    change_in_other_working_capital: Optional[float] = Field(None, description="Change in other working capital")
    change_in_other_current_liabilities: Optional[float] = Field(None, description="Change in other current liabilities")
    change_in_other_current_assets: Optional[float] = Field(None, description="Change in other current assets")
    change_in_payables_and_accrued_expense: Optional[float] = Field(None, description="Change in payables and accrued expense")
    change_in_payable: Optional[float] = Field(None, description="Change in payable")
    change_in_account_payable: Optional[float] = Field(None, description="Change in account payable")
    change_in_inventory: Optional[float] = Field(None, description="Change in inventory")
    change_in_receivables: Optional[float] = Field(None, description="Change in receivables")
    changes_in_account_receivables: Optional[float] = Field(None, description="Changes in account receivables")
    other_non_cash_items: Optional[float] = Field(None, description="Other non-cash items")
    stock_based_compensation: Optional[float] = Field(None, description="Stock-based compensation")
    deferred_tax: Optional[float] = Field(None, description="Deferred tax")
    deferred_income_tax: Optional[float] = Field(None, description="Deferred income tax")
    depreciation_amortization_depletion: Optional[float] = Field(None, description="Depreciation, amortization and depletion")
    depreciation_and_amortization: Optional[float] = Field(None, description="Depreciation and amortization")
    net_income_from_continuing_operations: Optional[float] = Field(None, description="Net income from continuing operations")
    date: Optional[datetime] = Field(None, description="Statement date")
