from typing import List, Optional
from pydantic import BaseModel, Field
from datetime import datetime


class FinancialItem(BaseModel):
    """Financial item"""
    date: Optional[datetime] = Field(None, description="Date and time")
    open: Optional[float] = Field(None, description="Opening price")
    high: Optional[float] = Field(None, description="Highest price")
    low: Optional[float] = Field(None, description="Lowest price")
    close: Optional[float] = Field(None, description="Closing price")
    volume: Optional[int] = Field(None, description="Trading volume")
    dividends: Optional[float] = Field(None, description="Dividends")
    stock_splits: Optional[float] = Field(None, description="Stock splits")

    market_cap: Optional[float] = Field(None, description="Market capitalization")
    enterprise_value: Optional[float] = Field(None, description="Enterprise value")
    dividends_and_other_cash_distributions: Optional[float] = Field(None, description="Dividends and other cash distributions")
    issuance_or_purchase_of_equity_shares: Optional[float] = Field(None, description="Issuance or purchase of equity shares")
    price_to_earnings_ratio: Optional[float] = Field(None, description="Price to earnings ratio")
    price_to_book_ratio: Optional[float] = Field(None, description="Price to book ratio")
    price_to_sales_ratio: Optional[float] = Field(None, description="Price to sales ratio")
    enterprise_value_to_ebitda_ratio: Optional[float] = Field(None, description="Enterprise value to EBITDA ratio")
    enterprise_value_to_revenue_ratio: Optional[float] = Field(None, description="Enterprise value to revenue ratio")
    free_cash_flow_yield: Optional[float] = Field(None, description="Free cash flow yield")
    peg_ratio: Optional[float] = Field(None, description="PEG ratio")
    gross_margin: Optional[float] = Field(None, description="Gross margin")
    operating_margin: Optional[float] = Field(None, description="Operating margin")
    net_margin: Optional[float] = Field(None, description="Net margin")
    return_on_equity: Optional[float] = Field(None, description="Return on equity")
    return_on_assets: Optional[float] = Field(None, description="Return on assets")
    return_on_invested_capital: Optional[float] = Field(None, description="Return on invested capital")
    asset_turnover: Optional[float] = Field(None, description="Asset turnover")
    inventory_turnover: Optional[float] = Field(None, description="Inventory turnover")
    receivables_turnover: Optional[float] = Field(None, description="Receivables turnover")
    days_sales_outstanding: Optional[float] = Field(None, description="Days sales outstanding")
    operating_cycle: Optional[float] = Field(None, description="Operating cycle")
    working_capital_turnover: Optional[float] = Field(None, description="Working capital turnover")
    current_ratio: Optional[float] = Field(None, description="Current ratio")
    quick_ratio: Optional[float] = Field(None, description="Quick ratio")
    cash_ratio: Optional[float] = Field(None, description="Cash ratio")
    operating_cash_flow_ratio: Optional[float] = Field(None, description="Operating cash flow ratio")
    debt_to_equity: Optional[float] = Field(None, description="Debt to equity ratio")
    debt_to_assets: Optional[float] = Field(None, description="Debt to assets ratio")
    interest_coverage: Optional[float] = Field(None, description="Interest coverage ratio")
    revenue_growth: Optional[float] = Field(None, description="Revenue growth rate")
    earnings_growth: Optional[float] = Field(None, description="Earnings growth rate")
    book_value_growth: Optional[float] = Field(None, description="Book value growth rate")
    earnings_per_share_growth: Optional[float] = Field(None, description="Earnings per share growth rate")
    free_cash_flow_growth: Optional[float] = Field(None, description="Free cash flow growth rate")
    operating_income_growth: Optional[float] = Field(None, description="Operating income growth rate")
    ebitda_growth: Optional[float] = Field(None, description="EBITDA growth rate")
    payout_ratio: Optional[float] = Field(None, description="Payout ratio")
    earnings_per_share: Optional[float] = Field(None, description="Earnings per share")
    book_value_per_share: Optional[float] = Field(None, description="Book value per share")
    free_cash_flow_per_share: Optional[float] = Field(None, description="Free cash flow per share")
    symbol: Optional[str] = Field(None, description="Stock symbol")

    """Single income statement item"""
    tax_effect_of_unusual_items: Optional[float] = Field(None, description="Tax effect of unusual items")
    tax_rate_for_calcs: Optional[float] = Field(None, description="Tax rate used for calculations")
    normalized_ebitda: Optional[float] = Field(None, description="Normalized EBITDA")
    net_income_from_continuing_operation_net_minority_interest: Optional[float] = Field(None, description="Net income from continuing operations net of minority interest")
    reconciled_depreciation: Optional[float] = Field(None, description="Reconciled depreciation")
    reconciled_cost_of_revenue: Optional[float] = Field(None, description="Reconciled cost of revenue")
    ebitda: Optional[float] = Field(None, description="EBITDA")
    ebit: Optional[float] = Field(None, description="EBIT")
    net_interest_income: Optional[float] = Field(None, description="Net interest income")
    interest_expense: Optional[float] = Field(None, description="Interest expense")
    interest_income: Optional[float] = Field(None, description="Interest income")
    normalized_income: Optional[float] = Field(None, description="Normalized income")
    net_income_from_continuing_and_discontinued_operation: Optional[float] = Field(None, description="Net income from continuing and discontinued operations")
    total_expenses: Optional[float] = Field(None, description="Total expenses")
    total_operating_income_as_reported: Optional[float] = Field(None, description="Total operating income as reported")
    diluted_average_shares: Optional[float] = Field(None, description="Diluted average shares")
    basic_average_shares: Optional[float] = Field(None, description="Basic average shares")
    diluted_eps: Optional[float] = Field(None, description="Diluted earnings per share")
    basic_eps: Optional[float] = Field(None, description="Basic earnings per share")
    diluted_niavailto_com_stockholders: Optional[float] = Field(None, description="Diluted net income available to common stockholders")
    net_income_common_stockholders: Optional[float] = Field(None, description="Net income to common stockholders")
    net_income: Optional[float] = Field(None, description="Net income")
    net_income_including_noncontrolling_interests: Optional[float] = Field(None, description="Net income including non-controlling interests")
    net_income_continuous_operations: Optional[float] = Field(None, description="Net income from continuous operations")
    tax_provision: Optional[float] = Field(None, description="Tax provision")
    pretax_income: Optional[float] = Field(None, description="Pre-tax income")
    other_income_expense: Optional[float] = Field(None, description="Other income/expense")
    other_non_operating_income_expenses: Optional[float] = Field(None, description="Other non-operating income/expenses")
    net_non_operating_interest_income_expense: Optional[float] = Field(None, description="Net non-operating interest income/expense")
    interest_expense_non_operating: Optional[float] = Field(None, description="Non-operating interest expense")
    interest_income_non_operating: Optional[float] = Field(None, description="Non-operating interest income")
    operating_income: Optional[float] = Field(None, description="Operating income")
    operating_expense: Optional[float] = Field(None, description="Operating expense")
    research_and_development: Optional[float] = Field(None, description="Research and development expenses")
    selling_general_and_administration: Optional[float] = Field(None, description="Selling, general and administration expenses")
    gross_profit: Optional[float] = Field(None, description="Gross profit")
    cost_of_revenue: Optional[float] = Field(None, description="Cost of revenue")
    total_revenue: Optional[float] = Field(None, description="Total revenue")
    operating_revenue: Optional[float] = Field(None, description="Operating revenue")

    """Single balance sheet item"""
    treasury_shares_number: Optional[float] = Field(None, description="Number of treasury shares")
    ordinary_shares_number: Optional[float] = Field(None, description="Number of ordinary shares")
    share_issued: Optional[float] = Field(None, description="Number of shares issued")
    net_debt: Optional[float] = Field(None, description="Net debt")
    total_debt: Optional[float] = Field(None, description="Total debt")
    tangible_book_value: Optional[float] = Field(None, description="Tangible book value")
    invested_capital: Optional[float] = Field(None, description="Invested capital")
    working_capital: Optional[float] = Field(None, description="Working capital")
    net_tangible_assets: Optional[float] = Field(None, description="Net tangible assets")
    capital_lease_obligations: Optional[float] = Field(None, description="Capital lease obligations")
    common_stock_equity: Optional[float] = Field(None, description="Common stock equity")
    total_capitalization: Optional[float] = Field(None, description="Total capitalization")
    total_equity_gross_minority_interest: Optional[float] = Field(None, description="Total equity including minority interest")
    stockholders_equity: Optional[float] = Field(None, description="Stockholders equity")
    gains_losses_not_affecting_retained_earnings: Optional[float] = Field(None, description="Gains/losses not affecting retained earnings")
    other_equity_adjustments: Optional[float] = Field(None, description="Other equity adjustments")
    retained_earnings: Optional[float] = Field(None, description="Retained earnings")
    capital_stock: Optional[float] = Field(None, description="Capital stock")
    common_stock: Optional[float] = Field(None, description="Common stock")
    total_liabilities_net_minority_interest: Optional[float] = Field(None, description="Total liabilities net of minority interest")
    total_non_current_liabilities_net_minority_interest: Optional[float] = Field(None, description="Total non-current liabilities net of minority interest")
    other_non_current_liabilities: Optional[float] = Field(None, description="Other non-current liabilities")
    tradeand_other_payables_non_current: Optional[float] = Field(None, description="Trade and other payables non-current")
    long_term_debt_and_capital_lease_obligation: Optional[float] = Field(None, description="Long-term debt and capital lease obligation")
    long_term_capital_lease_obligation: Optional[float] = Field(None, description="Long-term capital lease obligation")
    long_term_debt: Optional[float] = Field(None, description="Long-term debt")
    current_liabilities: Optional[float] = Field(None, description="Current liabilities")
    other_current_liabilities: Optional[float] = Field(None, description="Other current liabilities")
    current_deferred_liabilities: Optional[float] = Field(None, description="Current deferred liabilities")
    current_deferred_revenue: Optional[float] = Field(None, description="Current deferred revenue")
    current_debt_and_capital_lease_obligation: Optional[float] = Field(None, description="Current debt and capital lease obligation")
    current_capital_lease_obligation: Optional[float] = Field(None, description="Current capital lease obligation")
    current_debt: Optional[float] = Field(None, description="Current debt")
    other_current_borrowings: Optional[float] = Field(None, description="Other current borrowings")
    commercial_paper: Optional[float] = Field(None, description="Commercial paper")
    payables_and_accrued_expenses: Optional[float] = Field(None, description="Payables and accrued expenses")
    payables: Optional[float] = Field(None, description="Payables")
    total_tax_payable: Optional[float] = Field(None, description="Total tax payable")
    income_tax_payable: Optional[float] = Field(None, description="Income tax payable")
    accounts_payable: Optional[float] = Field(None, description="Accounts payable")
    total_assets: Optional[float] = Field(None, description="Total assets")
    total_non_current_assets: Optional[float] = Field(None, description="Total non-current assets")
    other_non_current_assets: Optional[float] = Field(None, description="Other non-current assets")
    non_current_deferred_assets: Optional[float] = Field(None, description="Non-current deferred assets")
    non_current_deferred_taxes_assets: Optional[float] = Field(None, description="Non-current deferred tax assets")
    investments_and_advances: Optional[float] = Field(None, description="Investments and advances")
    other_investments: Optional[float] = Field(None, description="Other investments")
    investmentin_financial_assets: Optional[float] = Field(None, description="Investment in financial assets")
    available_for_sale_securities: Optional[float] = Field(None, description="Available for sale securities")
    net_ppe: Optional[float] = Field(None, description="Net property, plant and equipment")
    accumulated_depreciation: Optional[float] = Field(None, description="Accumulated depreciation")
    gross_ppe: Optional[float] = Field(None, description="Gross property, plant and equipment")
    leases: Optional[float] = Field(None, description="Leases")
    other_properties: Optional[float] = Field(None, description="Other properties")
    machinery_furniture_equipment: Optional[float] = Field(None, description="Machinery, furniture and equipment")
    land_and_improvements: Optional[float] = Field(None, description="Land and improvements")
    properties: Optional[float] = Field(None, description="Properties")
    current_assets: Optional[float] = Field(None, description="Current assets")
    other_current_assets: Optional[float] = Field(None, description="Other current assets")
    inventory: Optional[float] = Field(None, description="Inventory")
    receivables: Optional[float] = Field(None, description="Receivables")
    other_receivables: Optional[float] = Field(None, description="Other receivables")
    accounts_receivable: Optional[float] = Field(None, description="Accounts receivable")
    cash_cash_equivalents_and_short_term_investments: Optional[float] = Field(None, description="Cash, cash equivalents and short-term investments")
    other_short_term_investments: Optional[float] = Field(None, description="Other short-term investments")
    cash_and_cash_equivalents: Optional[float] = Field(None, description="Cash and cash equivalents")
    cash_equivalents: Optional[float] = Field(None, description="Cash equivalents")
    cash_financial: Optional[float] = Field(None, description="Financial cash")

    """Single cash flow statement item"""
    free_cash_flow: Optional[float] = Field(None, description="Free cash flow")
    repurchase_of_capital_stock: Optional[float] = Field(None, description="Repurchase of capital stock")
    repayment_of_debt: Optional[float] = Field(None, description="Repayment of debt")
    issuance_of_debt: Optional[float] = Field(None, description="Issuance of debt")
    issuance_of_capital_stock: Optional[float] = Field(None, description="Issuance of capital stock")
    capital_expenditure: Optional[float] = Field(None, description="Capital expenditure")
    interest_paid_supplemental_data: Optional[float] = Field(None, description="Interest paid supplemental data")
    income_tax_paid_supplemental_data: Optional[float] = Field(None, description="Income tax paid supplemental data")
    end_cash_position: Optional[float] = Field(None, description="End cash position")
    beginning_cash_position: Optional[float] = Field(None, description="Beginning cash position")
    changes_in_cash: Optional[float] = Field(None, description="Changes in cash")
    financing_cash_flow: Optional[float] = Field(None, description="Financing cash flow")
    cash_flow_from_continuing_financing_activities: Optional[float] = Field(None, description="Cash flow from continuing financing activities")
    net_other_financing_charges: Optional[float] = Field(None, description="Net other financing charges")
    cash_dividends_paid: Optional[float] = Field(None, description="Cash dividends paid")
    common_stock_dividend_paid: Optional[float] = Field(None, description="Common stock dividend paid")
    net_common_stock_issuance: Optional[float] = Field(None, description="Net common stock issuance")
    common_stock_payments: Optional[float] = Field(None, description="Common stock payments")
    common_stock_issuance: Optional[float] = Field(None, description="Common stock issuance")
    net_issuance_payments_of_debt: Optional[float] = Field(None, description="Net issuance/payments of debt")
    net_short_term_debt_issuance: Optional[float] = Field(None, description="Net short-term debt issuance")
    net_long_term_debt_issuance: Optional[float] = Field(None, description="Net long-term debt issuance")
    long_term_debt_payments: Optional[float] = Field(None, description="Long-term debt payments")
    long_term_debt_issuance: Optional[float] = Field(None, description="Long-term debt issuance")
    investing_cash_flow: Optional[float] = Field(None, description="Investing cash flow")
    cash_flow_from_continuing_investing_activities: Optional[float] = Field(None, description="Cash flow from continuing investing activities")
    net_other_investing_changes: Optional[float] = Field(None, description="Net other investing changes")
    net_investment_purchase_and_sale: Optional[float] = Field(None, description="Net investment purchase and sale")
    sale_of_investment: Optional[float] = Field(None, description="Sale of investment")
    purchase_of_investment: Optional[float] = Field(None, description="Purchase of investment")
    net_business_purchase_and_sale: Optional[float] = Field(None, description="Net business purchase and sale")
    purchase_of_business: Optional[float] = Field(None, description="Purchase of business")
    net_ppe_purchase_and_sale: Optional[float] = Field(None, description="Net property, plant and equipment purchase and sale")
    purchase_of_ppe: Optional[float] = Field(None, description="Purchase of property, plant and equipment")
    operating_cash_flow: Optional[float] = Field(None, description="Operating cash flow")
    cash_flow_from_continuing_operating_activities: Optional[float] = Field(None, description="Cash flow from continuing operating activities")
    change_in_working_capital: Optional[float] = Field(None, description="Change in working capital")
    change_in_other_working_capital: Optional[float] = Field(None, description="Change in other working capital")
    change_in_other_current_liabilities: Optional[float] = Field(None, description="Change in other current liabilities")
    change_in_other_current_assets: Optional[float] = Field(None, description="Change in other current assets")
    change_in_payables_and_accrued_expense: Optional[float] = Field(None, description="Change in payables and accrued expense")
    change_in_payable: Optional[float] = Field(None, description="Change in payable")
    change_in_account_payable: Optional[float] = Field(None, description="Change in account payable")
    change_in_inventory: Optional[float] = Field(None, description="Change in inventory")
    change_in_receivables: Optional[float] = Field(None, description="Change in receivables")
    changes_in_account_receivables: Optional[float] = Field(None, description="Changes in account receivables")
    other_non_cash_items: Optional[float] = Field(None, description="Other non-cash items")
    stock_based_compensation: Optional[float] = Field(None, description="Stock-based compensation")
    deferred_tax: Optional[float] = Field(None, description="Deferred tax")
    deferred_income_tax: Optional[float] = Field(None, description="Deferred income tax")
    depreciation_amortization_depletion: Optional[float] = Field(None, description="Depreciation, amortization and depletion")
    depreciation_and_amortization: Optional[float] = Field(None, description="Depreciation and amortization")
    net_income_from_continuing_operations: Optional[float] = Field(None, description="Net income from continuing operations")
