from typing import List, Optional
from pydantic import BaseModel, Field
from datetime import datetime


class CompanyOfficer(BaseModel):
    """Company officer information"""
    max_age: Optional[int] = Field(None, description="Maximum age of the data")
    name: Optional[str] = Field(None, description="Name of the officer")
    age: Optional[int] = Field(None, description="Age of the officer")
    title: Optional[str] = Field(None, description="Title of the officer")
    year_born: Optional[int] = Field(None, description="Year the officer was born")
    fiscal_year: Optional[int] = Field(None, description="Fiscal year of the data")
    total_pay: Optional[float] = Field(None, description="Total compensation")
    exercised_value: Optional[float] = Field(None, description="Value of exercised options")
    unexercised_value: Optional[float] = Field(None, description="Value of unexercised options")


class CorporateActionMeta(BaseModel):
    """Corporate action metadata"""
    event_type: Optional[str] = Field(None, description="Type of corporate event")
    date_epoch_ms: Optional[int] = Field(None, description="Event date in epoch milliseconds")
    amount: Optional[str] = Field(None, description="Amount associated with the event")


class CorporateAction(BaseModel):
    """Corporate action information"""
    header: Optional[str] = Field(None, description="Header of the corporate action")
    message: Optional[str] = Field(None, description="Description of the corporate action")
    meta: Optional[CorporateActionMeta] = Field(None, description="Metadata of the corporate action")


class TickerInfo(BaseModel):
    """Ticker information response model"""
    address1: Optional[str] = Field(None, description="First line of the company address")
    city: Optional[str] = Field(None, description="City of the company")
    state: Optional[str] = Field(None, description="State of the company")
    zip: Optional[str] = Field(None, description="ZIP code of the company")
    country: Optional[str] = Field(None, description="Country of the company")
    phone: Optional[str] = Field(None, description="Phone number of the company")
    website: Optional[str] = Field(None, description="Website URL of the company")
    industry: Optional[str] = Field(None, description="Industry of the company")
    industry_key: Optional[str] = Field(None, description="Industry key")
    industry_disp: Optional[str] = Field(None, description="Industry display name")
    sector: Optional[str] = Field(None, description="Sector of the company")
    sector_key: Optional[str] = Field(None, description="Sector key")
    sector_disp: Optional[str] = Field(None, description="Sector display name")
    long_business_summary: Optional[str] = Field(None, description="Long business summary")
    full_time_employees: Optional[int] = Field(None, description="Number of full-time employees")
    company_officers: Optional[List[CompanyOfficer]] = Field(None, description="List of company officers")
    audit_risk: Optional[int] = Field(None, description="Audit risk score")
    board_risk: Optional[int] = Field(None, description="Board risk score")
    compensation_risk: Optional[int] = Field(None, description="Compensation risk score")
    share_holder_rights_risk: Optional[int] = Field(None, description="Shareholder rights risk score")
    overall_risk: Optional[int] = Field(None, description="Overall risk score")
    governance_epoch_date: Optional[int] = Field(None, description="Governance date in epoch format")
    compensation_as_of_epoch_date: Optional[int] = Field(None, description="Compensation date in epoch format")
    ir_website: Optional[str] = Field(None, description="Investor relations website")
    executive_team: Optional[List] = Field(None, description="Executive team information")
    max_age: Optional[int] = Field(None, description="Maximum age of the data")
    price_hint: Optional[int] = Field(None, description="Price hint")
    previous_close: Optional[float] = Field(None, description="Previous closing price")
    open: Optional[float] = Field(None, description="Opening price")
    day_low: Optional[float] = Field(None, description="Lowest price of the day")
    day_high: Optional[float] = Field(None, description="Highest price of the day")
    regular_market_previous_close: Optional[float] = Field(None, description="Previous close in regular market")
    regular_market_open: Optional[float] = Field(None, description="Opening price in regular market")
    regular_market_day_low: Optional[float] = Field(None, description="Lowest price of the day in regular market")
    regular_market_day_high: Optional[float] = Field(None, description="Highest price of the day in regular market")
    dividend_rate: Optional[float] = Field(None, description="Dividend rate")
    dividend_yield: Optional[float] = Field(None, description="Dividend yield")
    ex_dividend_date: Optional[int] = Field(None, description="Ex-dividend date in epoch format")
    payout_ratio: Optional[float] = Field(None, description="Payout ratio")
    five_year_avg_dividend_yield: Optional[float] = Field(None, description="5-year average dividend yield")
    beta: Optional[float] = Field(None, description="Beta value")
    trailing_pe: Optional[float] = Field(None, description="Trailing price-to-earnings ratio")
    forward_pe: Optional[float] = Field(None, description="Forward price-to-earnings ratio")
    volume: Optional[int] = Field(None, description="Trading volume")
    regular_market_volume: Optional[int] = Field(None, description="Trading volume in regular market")
    average_volume: Optional[int] = Field(None, description="Average trading volume")
    average_volume10days: Optional[int] = Field(None, description="Average volume over 10 days")
    average_daily_volume10_day: Optional[int] = Field(None, description="Average daily volume over 10 days")
    bid: Optional[float] = Field(None, description="Bid price")
    ask: Optional[float] = Field(None, description="Ask price")
    bid_size: Optional[int] = Field(None, description="Bid size")
    ask_size: Optional[int] = Field(None, description="Ask size")
    market_cap: Optional[float] = Field(None, description="Market capitalization")
    fifty_two_week_low: Optional[float] = Field(None, description="52-week low price")
    fifty_two_week_high: Optional[float] = Field(None, description="52-week high price")
    price_to_sales_trailing12_months: Optional[float] = Field(None, description="Price-to-sales ratio trailing 12 months")
    fifty_day_average: Optional[float] = Field(None, description="50-day average price")
    two_hundred_day_average: Optional[float] = Field(None, description="200-day average price")
    trailing_annual_dividend_rate: Optional[float] = Field(None, description="Trailing annual dividend rate")
    trailing_annual_dividend_yield: Optional[float] = Field(None, description="Trailing annual dividend yield")
    currency: Optional[str] = Field(None, description="Currency code")
    tradeable: Optional[bool] = Field(None, description="Whether the stock is tradeable")
    enterprise_value: Optional[float] = Field(None, description="Enterprise value")
    profit_margins: Optional[float] = Field(None, description="Profit margins")
    float_shares: Optional[int] = Field(None, description="Number of shares in float")
    shares_outstanding: Optional[int] = Field(None, description="Number of shares outstanding")
    shares_short: Optional[int] = Field(None, description="Number of shares sold short")
    shares_short_prior_month: Optional[int] = Field(None, description="Shares short in prior month")
    shares_short_previous_month_date: Optional[int] = Field(None, description="Date of previous month short data in epoch format")
    date_short_interest: Optional[int] = Field(None, description="Date of short interest in epoch format")
    shares_percent_shares_out: Optional[float] = Field(None, description="Percentage of shares sold short")
    held_percent_insiders: Optional[float] = Field(None, description="Percentage held by insiders")
    held_percent_institutions: Optional[float] = Field(None, description="Percentage held by institutions")
    short_ratio: Optional[float] = Field(None, description="Short ratio")
    short_percent_of_float: Optional[float] = Field(None, description="Short percentage of float")
    implied_shares_outstanding: Optional[int] = Field(None, description="Implied shares outstanding")
    book_value: Optional[float] = Field(None, description="Book value per share")
    price_to_book: Optional[float] = Field(None, description="Price-to-book ratio")
    last_fiscal_year_end: Optional[int] = Field(None, description="Last fiscal year end date in epoch format")
    next_fiscal_year_end: Optional[int] = Field(None, description="Next fiscal year end date in epoch format")
    most_recent_quarter: Optional[int] = Field(None, description="Most recent quarter date in epoch format")
    earnings_quarterly_growth: Optional[float] = Field(None, description="Quarterly earnings growth")
    net_income_to_common: Optional[float] = Field(None, description="Net income to common shareholders")
    trailing_eps: Optional[float] = Field(None, description="Trailing earnings per share")
    forward_eps: Optional[float] = Field(None, description="Forward earnings per share")
    last_split_factor: Optional[str] = Field(None, description="Last stock split factor")
    last_split_date: Optional[int] = Field(None, description="Last stock split date in epoch format")
    enterprise_to_revenue: Optional[float] = Field(None, description="Enterprise value to revenue ratio")
    enterprise_to_ebitda: Optional[float] = Field(None, description="Enterprise value to EBITDA ratio")
    week_52_change: Optional[float] = Field(None, description="52-week change percentage")
    sand_p52_week_change: Optional[float] = Field(None, description="S&P 500 52-week change percentage")
    last_dividend_value: Optional[float] = Field(None, description="Last dividend value")
    last_dividend_date: Optional[int] = Field(None, description="Last dividend date in epoch format")
    quote_type: Optional[str] = Field(None, description="Quote type")
    current_price: Optional[float] = Field(None, description="Current price")
    target_high_price: Optional[float] = Field(None, description="High target price")
    target_low_price: Optional[float] = Field(None, description="Low target price")
    target_mean_price: Optional[float] = Field(None, description="Mean target price")
    target_median_price: Optional[float] = Field(None, description="Median target price")
    recommendation_mean: Optional[float] = Field(None, description="Mean recommendation")
    recommendation_key: Optional[str] = Field(None, description="Recommendation key")
    number_of_analyst_opinions: Optional[int] = Field(None, description="Number of analyst opinions")
    total_cash: Optional[float] = Field(None, description="Total cash")
    total_cash_per_share: Optional[float] = Field(None, description="Total cash per share")
    ebitda: Optional[float] = Field(None, description="EBITDA")
    total_debt: Optional[float] = Field(None, description="Total debt")
    quick_ratio: Optional[float] = Field(None, description="Quick ratio")
    current_ratio: Optional[float] = Field(None, description="Current ratio")
    total_revenue: Optional[float] = Field(None, description="Total revenue")
    debt_to_equity: Optional[float] = Field(None, description="Debt to equity ratio")
    revenue_per_share: Optional[float] = Field(None, description="Revenue per share")
    return_on_assets: Optional[float] = Field(None, description="Return on assets")
    return_on_equity: Optional[float] = Field(None, description="Return on equity")
    gross_profits: Optional[float] = Field(None, description="Gross profits")
    free_cashflow: Optional[float] = Field(None, description="Free cash flow")
    operating_cashflow: Optional[float] = Field(None, description="Operating cash flow")
    earnings_growth: Optional[float] = Field(None, description="Earnings growth")
    revenue_growth: Optional[float] = Field(None, description="Revenue growth")
    gross_margins: Optional[float] = Field(None, description="Gross margins")
    ebitda_margins: Optional[float] = Field(None, description="EBITDA margins")
    operating_margins: Optional[float] = Field(None, description="Operating margins")
    financial_currency: Optional[str] = Field(None, description="Financial currency code")
    symbol: Optional[str] = Field(None, description="Stock symbol")
    language: Optional[str] = Field(None, description="Language")
    region: Optional[str] = Field(None, description="Region")
    type_disp: Optional[str] = Field(None, description="Type display")
    quote_source_name: Optional[str] = Field(None, description="Quote source name")
    triggerable: Optional[bool] = Field(None, description="Whether the quote is triggerable")
    custom_price_alert_confidence: Optional[str] = Field(None, description="Custom price alert confidence")
    has_pre_post_market_data: Optional[bool] = Field(None, description="Whether pre/post market data is available")
    first_trade_date_milliseconds: Optional[int] = Field(None, description="First trade date in milliseconds")
    post_market_change_percent: Optional[float] = Field(None, description="Post-market change percentage")
    post_market_price: Optional[float] = Field(None, description="Post-market price")
    post_market_change: Optional[float] = Field(None, description="Post-market change")
    regular_market_change: Optional[float] = Field(None, description="Regular market change")
    regular_market_day_range: Optional[str] = Field(None, description="Regular market day range")
    full_exchange_name: Optional[str] = Field(None, description="Full exchange name")
    average_daily_volume3_month: Optional[int] = Field(None, description="Average daily volume over 3 months")
    fifty_two_week_low_change: Optional[float] = Field(None, description="52-week low price change")
    fifty_two_week_low_change_percent: Optional[float] = Field(None, description="52-week low price change percentage")
    fifty_two_week_range: Optional[str] = Field(None, description="52-week price range")
    fifty_two_week_high_change: Optional[float] = Field(None, description="52-week high price change")
    fifty_two_week_high_change_percent: Optional[float] = Field(None, description="52-week high price change percentage")
    fifty_two_week_change_percent: Optional[float] = Field(None, description="52-week change percentage")
    dividend_date: Optional[int] = Field(None, description="Dividend date in epoch format")
    earnings_timestamp: Optional[int] = Field(None, description="Earnings timestamp")
    earnings_timestamp_start: Optional[int] = Field(None, description="Earnings start timestamp")
    earnings_timestamp_end: Optional[int] = Field(None, description="Earnings end timestamp")
    earnings_call_timestamp_start: Optional[int] = Field(None, description="Earnings call start timestamp")
    earnings_call_timestamp_end: Optional[int] = Field(None, description="Earnings call end timestamp")
    is_earnings_date_estimate: Optional[bool] = Field(None, description="Whether earnings date is estimated")
    short_name: Optional[str] = Field(None, description="Short name of the company")
    long_name: Optional[str] = Field(None, description="Long name of the company")
    corporate_actions: Optional[List[CorporateAction]] = Field(None, description="List of corporate actions")
    post_market_time: Optional[int] = Field(None, description="Post-market time")
    regular_market_time: Optional[int] = Field(None, description="Regular market time")
    exchange: Optional[str] = Field(None, description="Exchange code")
    message_board_id: Optional[str] = Field(None, description="Message board ID")
    exchange_timezone_name: Optional[str] = Field(None, description="Exchange timezone name")
    exchange_timezone_short_name: Optional[str] = Field(None, description="Exchange timezone short name")
    gmt_off_set_milliseconds: Optional[int] = Field(None, description="GMT offset in milliseconds")
    market: Optional[str] = Field(None, description="Market")
    esg_populated: Optional[bool] = Field(None, description="Whether ESG data is populated")
    eps_trailing_twelve_months: Optional[float] = Field(None, description="EPS trailing twelve months")
    eps_forward: Optional[float] = Field(None, description="Forward EPS")
    eps_current_year: Optional[float] = Field(None, description="Current year EPS")
    price_eps_current_year: Optional[float] = Field(None, description="Price to current year EPS ratio")
    fifty_day_average_change: Optional[float] = Field(None, description="50-day average price change")
    fifty_day_average_change_percent: Optional[float] = Field(None, description="50-day average price change percentage")
    two_hundred_day_average_change: Optional[float] = Field(None, description="200-day average price change")
    two_hundred_day_average_change_percent: Optional[float] = Field(None, description="200-day average price change percentage")
    source_interval: Optional[int] = Field(None, description="Source interval")
    exchange_data_delayed_by: Optional[int] = Field(None, description="Exchange data delay in minutes")
    average_analyst_rating: Optional[str] = Field(None, description="Average analyst rating")
    crypto_tradeable: Optional[bool] = Field(None, description="Whether the cryptocurrency is tradeable")
    regular_market_change_percent: Optional[float] = Field(None, description="Regular market change percentage")
    regular_market_price: Optional[float] = Field(None, description="Regular market price")
    market_state: Optional[str] = Field(None, description="Market state")
    display_name: Optional[str] = Field(None, description="Display name")
    trailing_peg_ratio: Optional[float] = Field(None, description="Trailing PEG ratio")